// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

	int a= Integer.parseInt(args[0]);
	int count1=0;
	int count2=0;
		
	for (int i = 0; i < a; i++) 
	{
		if (Math.random()>0.5)
			count1++;
		else
			count2++;
	}

	if ((count1 != 0) && (count2 != 0)) 
	{ 
	  System.out.println("> 0.5: "+count1+ " times");
	  System.out.println("<= 0.5: "+count2+ " times");
	  double ratio= Math.min((double) count1,count2)/Math.max((double) count1,count2);
	  System.out.println("Ratio: "+ ratio);
    }

	else
	{
	  System.out.println("> 0.5: "+count1+ " times");
	  System.out.println("<= 0.5: "+count2+ " times");
	}
}
}
